---
title: "GHA maize yield gap"
author:
- affiliation: Wageningen Economic Research & IIASA
  name: Michiel van Dijk
- affiliation: Wageningen Economic Research
  name: Zuzana Smeets Kristkova
- affiliation: Wageningen Economic Research
  name: Tom Morley
- affiliation: Ethiopian Economic Policy Research Institute
  name: Assefa Admassie
- affiliation: ADD
  name: Lenny van Bussel
  
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    number_sections: yes
    template: D:\\Dropbox\\Michiel_research\\Templates\\r-markdown-templates\\svm-latex-ms.tex
  html_document: default
  word_document: default
fontsize: 11pt
geometry: margin=1in
keywords: Yield Gap
bibliography: M:/My Documents/bibTex/library.bib
subtitle: Check
thanks: "**Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: michiel.vandijk@wur.nl."
abstract: ETH Maize yield gaps abstract
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


# Introduction

# Background


# Methodology

We use a stochastic frontier production function [@Aigner1977; @Meeusen1977] to estimate the technical efficiency yield gap. The model is specified as follows for our study:

\begin{equation}
\label{sfa}
y_i=x_i\beta+v_i-u_i
\end{equation}

where, $y_i$ is the logarithm of actual yield (ya) for maize plot $i$, $x_i$ is a vector containing growth defining, growth limiting and growth reducing factors a set of control variables, $\beta$ is a vector of parameters, $v_i$  is a symmetric random error and $u_i$ is non-negative random variable with a half normal distribution that measures technical inefficiency. 

The coefficients in equation [X] will be biased if we do not correct for time-invariant unobserved heterogeneity and endogeneity of inputs [REF]. Examples of the former are farmer's management capacity and soil quality, which are expected to affect crop yield. Both are probably known to the farmer  but are only partially captured by our explanatory factors. Examples of time-variant heterogeneity are a[ADD]. 

To control for time-invariant unobserved heterogeneity, we apply the correlated random effects (CRE) estimator [@Wooldridge2002], which is also referred to as the Mundlak-Chamberlain device, following the work of Mundlak [-@Mundlak1978] and Chamberlain [-@Chamberlain1984]. CRE is the standard approach in recent and similar micro-econometric studies that use panel data to control for time-invariant heterogeneity [e.g. @Mason2013; @Mason2013a; @Sheahan2013] and can also be combined with stochastic frontier analysis [@Farsi2006; @Abdulai2007]. Although it results in similar outcomes as the fixed effects estimator [ADD], it has the major advantage that it can also be applied to unbalanced samples [REF]. This is particularly relevant for our case where the number of observations differs considerable between the first and second year due a design flaw in the survey (see below). A second advantage is that the impact of higher  level explanatory factors, such as farm machinery that are defined at the household level, can be measured.  

The CRE estimator allows for correlation between the time invariant unobserved household specific omitted variable and the explanatory variables. The technique is implemented by modelling the distribution of the omitted variable, conditional on the means of the strictly exogenous variables: 

[ADD eq]

The yield response function (Equation [X]) includes several endogenous farm inputs (i.e. area, labour, fertilizer and capital). Under perfect markets the demand for inputs only depends on the prices for inputs and outputs and technology XX [REF]. In developing countries, where the assumption of perfect markets is not tenable [REF], input use also depends on household and [XX] factors. To control for endogeneity we implement a control function approach [REF].[ADD]. The advantage of the control function approach in comparison to two stage least squares [CHECK] is that it can be combined with non-linear  functions such as the translog stochastic frontier function [@Amsler2016]. Wooldridge [REF] shows that, with certain assumptions, only one residual is required to instrument the endogenous variable and all its transformations (i.e. the squared and interaction terms in the translog model).

Although all inputs are potentially endogenous in equation X, we only estimate the demand function for the use of fertilizer, which is a key variable in our analysis. [MAYBE add for labour to]. For land and labour we estimate a OLS function as these are continous input variables. Fertilizer is only applied to [X]% of the plots. Following We use a tobit function to take this into account [TERMINOLOGY]. Following other research that estimate input demand functions [REF], we include all exogenous variables from equation [X] as well plot (e.g. soil quality, ...[ADD] and household (e.g. age and sex of the household head, household composition and [ADD] factors that are expected to affect input use. Similarly to the estimation of the stochastic frontier function, we apply the CRE framework to account for time-variant unobserved heterogeneity.

l exogenous factors in equation [X] as well as household and plot specific factors. For We estimate the following demand functions. For land and labour we  

# Data


# Results

# Conclusions

